### PR TITLE
Upgrade mysql + integrate with auth interface.

### PR DESCRIPTION
**Pull request by kuba--**
Signed-off-by: kuba-- <kuba@sourced.tech>

Closes https://github.com/src-d/go-mysql-server/issues/468

### CODE REVIEW

**Comment by ajnavarro** [comment]
@kuba-- could you have a look at Javi's comment? After that LGTM.

**Comment by kuba--** [comment]
@jfontan - now we have nice/colourful audit logs in gitbase ;)

**Comment by ajnavarro** [comment]
@kuba-- I don't know what is happening with Travis, it is not triggered. Can you rebase pleas?

**Comment by kuba--** [comment]
@ajnavarro - done

**Pull request merged**
