### PR TITLE
vendor: upgrade go-mysql-server

### PR DESCRIPTION
**Pull request by ajnavarro**
Signed-off-by: Antonio Jesus Navarro Perez <antnavper@gmail.com>

### CODE REVIEW

**Comment by ajnavarro** [comment]
@erizocosmico done

**Comment by ajnavarro** [comment]
@erizocosmico @kuba-- PTAL

**Comment by kuba--** [comment]
@ajnavarro - do we need to vendor this integration test?
` vendor/gopkg.in/src-d/go-mysql-server.v0/_integration/c/test.c`
As far as I see we don't vendor `_integration` folder.

**Comment by ajnavarro** [comment]
@kuba-- removed unused packages

**Pull request merged**
