### PR TITLE
*: implement indexable interfaces on basic and relation tables

### LINKED ISSUE #253: Implement Table Indexable interface
Depends on: https://github.com/src-d/go-mysql-server/issues/169

### PR DESCRIPTION
**Pull request by mcarmonaa**
Depends on [src-d/go-mysql-server] PRs:
- https://github.com/src-d/go-mysql-server/pull/181, until this is merged, the `go-mysql-server` dependency can't be updated because of tests failing. Also here is implemented the method `IndexOf` for the schema which is used by the `IndexKeyValueIter` method

- https://github.com/src-d/go-mysql-server/pull/206, until this is merged, the `go-mysql-server` dependency can't be updated because of tests failing.

- https://github.com/src-d/go-mysql-server/pull/193, in this PR `sql.Context` is added to the `sql.Indexable` interfaces. This change is needed to have access to the repository pool from the `sql.Indexable` methods implementation.

@src-d/data-retrieval just have a look to the proposed implementation, if all is ok I'll address the dependency update.

Signed-off-by: Manuel Carmona <manu.carmona90@gmail.com>

### CODE REVIEW

**Comment by erizocosmico** [comment]
Needs rebase

**Comment by mcarmonaa** [comment]
@erizocosmico, rebased!

**Comment by erizocosmico** [comment]
@mcarmonaa @ajnavarro since as of #295 the indexes are going to work with `packfile.Decoder` instead of `Repository`, should we close this and implement it on the PR after #295 or do you think there is anything we should keep from this PR?

**Comment by ajnavarro** [comment]
@erizocosmico yeah, maybe we should get as much as we can from this PR, and define the new index values per table.

**Comment by erizocosmico** [comment]
Ok, will merge this in another branch and then go from here.

**Pull request merged**
