### PR TITLE
Implement indexes

### LINKED ISSUE #253: Implement Table Indexable interface
Depends on: https://github.com/src-d/go-mysql-server/issues/169

### PR DESCRIPTION
**Pull request by erizocosmico**
Closes #253 

We should be able to release a version with indexes after this.

### CODE REVIEW

**Comment by ajnavarro** [comment]
Appears that is out of date with master, can you rebase it?

**Comment by ajnavarro** [comment]
@erizocosmico LGTM

**Comment by erizocosmico** [comment]
That's weird, let me investigate

**Comment by erizocosmico** [comment]
Upgraded go-mysql-server with the fixes for the issues you mentioned

**Comment by erizocosmico** [comment]
Updated go-mysql-server with `DROP INDEX` statement

**Comment by ajnavarro** [comment]
@erizocosmico there is something missing from go-mysql-server or can we upload it to latest master version?

**Comment by ajnavarro** [comment]
I think this is missed: https://github.com/src-d/go-mysql-server/pull/223

**Comment by erizocosmico** [comment]
Yes, that was missing, I'll update that

**Pull request merged**
