### PR TITLE
vendor: upgrade go-mysql-server

### LINKED ISSUE #799: table "commits" does not have column "repository_id"
I got this error making charts in superset but the smallest reproducible sql is:

```sql
SELECT repository_id AS repository_id
FROM commits
GROUP BY repository_id
ORDER BY repository_id
```

### PR DESCRIPTION
**Pull request by erizocosmico**
Closes #799

### CODE REVIEW

**Comment by erizocosmico** [comment]
Don't merge, there is a regression.

**Comment by erizocosmico** [comment]
I'm gonna keep this blocked until HAVING is merged, which fixed a regression as well.

**Comment by erizocosmico** [comment]
Ready to be merged

**Comment by ajnavarro** [comment]
@erizocosmico I think you will need to update go-vitess dependency

**Comment by erizocosmico** [comment]
Should be fixed now. dep didn't notice the update in go-mysql-server without adding a new override for go-vitess.

**Comment by erizocosmico** [comment]
Delaying this again to squeeze https://github.com/src-d/go-mysql-server/pull/697 in

**Comment by erizocosmico** [comment]
Ready to be merged

**Pull request merged**
