### PR TITLE
internal/rule: fix projections when squash joins

### LINKED ISSUE #388: Bad project resolution on tree_entries
Executing this query:
```sql
SELECT 
	c.commit_hash AS hash, 
	c.committer_when AS date, 
	commit_author_name AS author, 
	te.tree_entry_name AS file 
FROM 
	commits c 
NATURAL JOIN commit_trees 
NATURAL JOIN tree_entries as te 
WHERE 
	c.repository_id="google/go-github";

```

`tree_entry_name` contains the `commit_hash`

Also, if I try to execute the following query (changing tree_entry_name to tree_hash):
```sql
mysql> SELECT  c.commit_hash AS hash,  c.committer_when AS date,  commit_author_name AS author,  te.tree_hash AS file  FROM  commits c  NATURAL JOIN commit_trees  NATURAL JOIN tree_entries as te  WHERE  c.repository_id="google/go-github"; 
ERROR 1105 (HY000): unknown error: table "tree_entries" does not have column "tree_hash"
mysql> describe table tree_entries;
+-----------------+------+
| name            | type |
+-----------------+------+
| repository_id   | TEXT |
| tree_entry_name | TEXT |
| blob_hash       | TEXT |
| tree_hash       | TEXT |
| tree_entry_mode | TEXT |
+-----------------+------+
5 rows in set (0,00 sec)
```

### PR DESCRIPTION
**Pull request by mcarmonaa**
Fixes #388 

This PR fix partially the bug. The other part of the fix is in https://github.com/src-d/go-mysql-server/pull/296.

When that PR in go-mysql-server is merged, I'll update the dependency in this PR and then the CI should pass the tests I added.

### CODE REVIEW

**Comment by ajnavarro** [comment]
@mcarmonaa please have a look into Travis.

**Comment by ajnavarro** [comment]
LGTM after update go-mysql-server dependency with the fix.

**Comment by ajnavarro** [comment]
@mcarmonaa I think you can update that now

**Comment by mcarmonaa** [comment]
@ajnavarro I'm on it, but I've found something wasn't well resolved in the previous go-mysql-server fix so I'm trying to fix it to make it work properly.

So this PR can't be merged until this other fix.

**Comment by mcarmonaa** [comment]
@ajnavarro PR ready to be merged

**Pull request merged**
