### PR TITLE
cmd/server/commands: use relative path as id instead of last part

### LINKED ISSUE #681: Use full path as repository_id
I have a repos structure like

```
/repositories
 - /owner
    - /repo
```

Sometimes repo names can be the same. In such case on gitbase start I see in logs:
```
time="2019-01-23T12:04:32Z" level=debug msg="repository added" path=/mnt/repositories/SignalR/SignalR
time="2019-01-23T12:04:32Z" level=error msg="repository could not be added" error="the repository is already registered: /mnt/repositories/SignalR/SignalR" id=SignalR path=/mnt/repositories/aspnet/SignalR
time="2019-01-23T12:04:32Z" level=debug msg="repository added" path=/mnt/repositories/aspnet/SignalR
```

Repos https://github.com/aspnet/SignalR and https://github.com/SignalR/SignalR are actually different but only one gets registered and available to query.

### PR DESCRIPTION
**Pull request by erizocosmico**
Fixes #681

Still can have collisions, but reduces the probability of having them.

Signed-off-by: Miguel Molina <miguel@erizocosmi.co>

### CODE REVIEW

**Comment by erizocosmico** [comment]
@kuba-- why would you want to store all paths in unix format?

**Comment by kuba--** [comment]
@erizocosmico - just to have it internally consistent (like you start gitbase on some OS and query on another). Like you have inside a zip file - all entries have unix separator(`/`) even if you use windows or pass `\`

**Comment by erizocosmico** [comment]
Sounds good to me

**Comment by juanjux** [comment]
Windows 10 will accept / and \ as path separators, don't know about previous versions, anyway unifying doesn't hurt.

**Pull request merged**
