### PR TITLE
gitbase: ignore .DS_Store files in darwin

### LINKED ISSUE #337: TestPatternMatches fails on macOS
It also matches `.DS_Store` on macOS, which makes it fail. We could have a different implementation for `darwin`, which ignores `.DS_Store` files.

### PR DESCRIPTION
**Pull request by erizocosmico**
Closes #337

### CODE REVIEW

**Comment by jfontan** [comment]
LGTM but I believe that we can simplify this and do it for all OSs. It can happen that we copy repos from MAC to Linux and have the same problem.

**Comment by erizocosmico** [comment]
Yep, we can probably unify this

**Comment by ajnavarro** [comment]
should we ignore all hidden files and folders? WDYT @jfontan @erizocosmico

**Comment by erizocosmico** [comment]
Regarding the comment from @ajnavarro in #341: we cannot ignore all hidden files and folders by default. They may have some meaning in the repository. Take into account `.travis.yml` and the bazillion `.something` JavaScript projects have.

**Comment by erizocosmico** [comment]
Shall we merge this?

**Comment by ajnavarro** [comment]
@erizocosmico rebase please

**Comment by erizocosmico** [comment]
Done

**Comment by ajnavarro** [comment]
@erizocosmico yes please.

**Pull request merged**
