### PR TITLE
 gitbase: implement files table with pushdown 

### LINKED ISSUE #269: Create new table: files
Create a new table with the following columns:

Files Table
--
repository_id
file_path
blob_hash
tree_hash
tree_entry_mode
blob_content
blob_size

### PR DESCRIPTION
**Pull request by erizocosmico**
Closes #269 

Depends on #275

### CODE REVIEW

**Comment by erizocosmico** [comment]
Rebased

**Comment by erizocosmico** [comment]
PTAL @ajnavarro

**Comment by ajnavarro** [comment]
@erizocosmico rebase please

**Comment by erizocosmico** [comment]
Rebased

**Comment by ajnavarro** [comment]
@erizocosmico yes

**Pull request merged**
