### PR TITLE
Upgrade mysql

### PR DESCRIPTION
**Pull request by kuba--**
Signed-off-by: kuba-- <kuba@sourced.tech>
This PR upgrades mysql dependency. New mysql-server contains the second part of closed iterators fix and makes go regex as a default engine.
At the same time (having go regex as a default) it closes https://github.com/src-d/gitbase/issues/778

### CODE REVIEW

**Comment by juanjux** [comment]
Shouldn't this update the Makefile too to remove the go regex build tag?

**Comment by kuba--** [comment]
yeah, I'll update it. but frankly this tag it's not used anymore

**Comment by erizocosmico** [comment]
Version test is not passing

**Comment by kuba--** [comment]
Yes, fixing (count is now int64)

**Comment by kuba--** [comment]
fixed.

**Pull request merged**
