### PR TITLE
vendor: upgrade go-mysql-server

### LINKED ISSUE #481: query from examples failing
This query results in error `: unknown error: unable to find field with index 10 in row of 8 columns`:
```sql
select
    files.file_path,
    ref_commits.repository_id,
    files.blob_content
FROM
    files
NATURAL JOIN
    commit_files
NATURAL JOIN
    ref_commits
WHERE
    ref_commits.ref_name = 'HEAD'
    AND ref_commits.history_index BETWEEN 0 AND 5
    AND is_binary(blob_content) = false
    AND files.file_path NOT REGEXP '^vendor.*'
    AND (
        blob_content REGEXP '(?i)facebook.*[\'\\"][0-9a-f]{32}[\'\\"]'
        OR blob_content REGEXP '(?i)twitter.*[\'\\"][0-9a-zA-Z]{35,44}[\'\\"]'
        OR blob_content REGEXP '(?i)github.*[\'\\"][0-9a-zA-Z]{35,40}[\'\\"]'
        OR blob_content REGEXP 'AKIA[0-9A-Z]{16}'
        OR blob_content REGEXP '(?i)reddit.*[\'\\"][0-9a-zA-Z]{14}[\'\\"]'
        OR blob_content REGEXP '(?i)heroku.*[0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12}'
        OR blob_content REGEXP '.*-----BEGIN PRIVATE KEY-----.*'
        OR blob_content REGEXP '.*-----BEGIN RSA PRIVATE KEY-----.*'
        OR blob_content REGEXP '.*-----BEGIN DSA PRIVATE KEY-----.*'
        OR blob_content REGEXP '.*-----BEGIN OPENSSH PRIVATE KEY-----.*'
    );
```

### PR DESCRIPTION
**Pull request by erizocosmico**
Fixes #481

### CODE REVIEW

**Comment by ajnavarro** [comment]
@erizocosmico can you have a quick look, please?

**Comment by erizocosmico** [comment]
Sure @ajnavarro

**Comment by erizocosmico** [comment]
Update had breaking changes and forgot to update them. Should be fine now

**Comment by erizocosmico** [comment]
It's still failing, looking into it

**Comment by ajnavarro** [comment]
@erizocosmico can you update it again please?

**Comment by erizocosmico** [comment]
done

**Comment by erizocosmico** [comment]
Fixed again, required some changes here this time

**Pull request merged**
