### PR TITLE
Regression queries

### PR DESCRIPTION
**Pull request by kuba--**
Signed-off-by: kuba-- <kuba@sourced.tech>

I'd like to add a file with regression queries. `regression-gitbase` will look into this file. If file doesn't exist (e.g. because of old version of gitbase) it will be tested against the default set of queries (like it worked before).

### CODE REVIEW

**Comment by jfontan** [comment]
I also believe that we should add some kind of unique ID. The format of it I'm not sure. If it's a string we can start with `Q1`, `Q2`... as @smola proposed and maybe move to something more meaningful in the future. Maybe grouping queries (`index1`, `uast7`).

**Comment by kuba--** [comment]
Ok, I added IDs. In `regression-gitbase` it will be parsed to string, but right now, because I don't have a good proposal for naming convention (maybe it should start from semver), I've put just numbers.

**Comment by erizocosmico** [comment]
Why do we need the version in the ID?

**Comment by jfontan** [comment]
I believe that `Q-1`, `Q-2` would be good enough now. Does anyone has a better idea? @ajnavarro, @smola?

**Comment by kuba--** [comment]
...renamed IDs to follow `queryX` convention.

**Comment by kuba--** [comment]
@ajnavarro - added test to parse regression queries.

**Pull request merged**
