### PR TITLE
mysql-upgrade target

### PR DESCRIPTION
**Pull request by kuba--**
Signed-off-by: kuba-- <kuba@sourced.tech>

command `make mysql-upgrade` upgrades mysql to the latest (master) revision

### CODE REVIEW

**Comment by kuba--** [comment]
whatever just something what we can easily remember (like we have dependencies :))

**Comment by kuba--** [comment]
we may also have sth. more generic:
```
make PRJ="gopkg.in/src-d/go-mysql-server.v0" upgrade
```

**Comment by erizocosmico** [comment]
That IMHO is a little bit verbose

**Comment by kuba--** [comment]
we may always have something short:
`make upgrade`
and if some day we will have to upgrade any other project then we may split this target into two or add another `go run tools/rev-upgrade/main.go` under the same `upgrade` target.

**Comment by ajnavarro** [comment]
@kuba-- go with `make upgrade`

**Comment by kuba--** [comment]
OK, I've changed it to: `make upgrade`.

By default it upgrades mysql, but if we want to apply upgrade to any different project we can do it by: 
```
make UPGRADE_PRJ="project name" UPGRADE_REV="revision number" upgrade
```

**Pull request merged**
