### PR TITLE
rule: fix squash rule with convert_dates

### LINKED ISSUE #826: Squash joins conflict with convert_dates
```
MySQL [(none)]> SELECT f.file_path, loc(f.file_path, f.blob_content) as loc_value, c.commit_author_when
    -> FROM repositories r
    -> NATURAL JOIN commits c
    -> NATURAL JOIN commit_files cf
    -> NATURAL JOIN files f
    -> WHERE r.repository_id = 'go-git' AND c.commit_hash = 'bbc05c7e371c19c3d85bf394b24061096a2b9a25'
    -> AND f.file_path NOT REGEXP '^vendor.*'
    -> AND NOT IS_BINARY(f.blob_content)
    -> AND loc_value IS NOT null
    -> LIMIT 10;
ERROR 1105 (HY000): unknown error: unable to find field with index 11 in row of 10 columns
MySQL [(none)]> select version();
+--------------------+
| VERSION()          |
+--------------------+
| 8.0.11-v0.20.0-rc2 |
+--------------------+
1 row in set (0.00 sec)
 ```

### PR DESCRIPTION
**Pull request by erizocosmico**
Fixes #826

### CODE REVIEW

**Comment by kuba--** [comment]
LGTM if tests pass

**Comment by erizocosmico** [comment]
Tests should be fixed now

**Comment by ajnavarro** [comment]
could you rebase please?

**Comment by erizocosmico** [comment]
Rebased

**Pull request merged**
