### PR TITLE
*: replace pilosalib with new pilosa driver

### PR DESCRIPTION
**Pull request by erizocosmico**
Will fail until https://github.com/src-d/go-mysql-server/pull/373 is merged and this is updated

### CODE REVIEW

**Comment by jfontan** [comment]
As @kuba-- said in go-mysql-server issue it would be nice to add a note in the documentation to migrate from old pilosa driver. This may be done after the code is merged.

**Comment by kuba--** [comment]
now, tests are failing

**Comment by erizocosmico** [comment]
@kuba-- yep:

> Will fail until src-d/go-mysql-server#373 is merged and this is updated

**Comment by erizocosmico** [comment]
Should be fixed now

**Comment by kuba--** [comment]
Still failing, because of integration tests. For instance we have just one constructor `NewDriver`, now.

**Pull request merged**
