### PR TITLE
Fix minor typo in README

### PR DESCRIPTION
**Pull request by sumbach**
Nice project, @erizocosmico @ajnavarro @jfontan 😄

### CODE REVIEW

**Comment by jfontan** [comment]
Thanks for the contribution @sumbach! We need all the commits signed off. You have more information here:

https://github.com/probot/dco#how-it-works

You can do that easily for this contribution with:

```
$ git commit --amend -s
$ git push --force
```

**Comment by sumbach** [comment]
Feel free to merge without sign-off or apply to change separately from this PR. It's a small typo fix--too small/trivial to be subject to copyright: https://softwareengineering.stackexchange.com/questions/195800/open-source-copyright-and-trivial-bugfixes

**Comment by smola** [comment]
Thanks @sumbach. I've just asked confirmation here: https://github.com/src-d/guide/issues/224
We will just merge if we get confirmed that we can.

We are sorry that this creates weird frictions, but we're still polishing some aspects of our copyright policies. Please, bear with us ;)

**Comment by sumbach** [comment]
No problem, @smola! Thanks for the response 😄 

I edited the README, made the branch, and opened the PR entirely from the github.com web interface, so the option to `git commit --amend` is not immediately at hand. Wonder if there's a way to add sign-off via the github.com web interface?

**Comment by erizocosmico** [comment]
@sumbach I think there is no such option in the GitHub UI.

**Comment by smola** [comment]
@ajnavarro We've got confirmation that we can merge this kind of PR (e.g. typo fixing) without sign-off, so feel free to merge this.

**Comment by ajnavarro** [comment]
Thanks a lot @sumbach !

**Pull request merged**
