### PR TITLE
 internal/function: do not make requests to bblfsh for unsupported languages

### LINKED ISSUE #325: UAST tries to extract uast even when the language is not supported
bblfsh now has a way to get supported languages, we can use this now to not send these blobs to bblfsh

### PR DESCRIPTION
**Pull request by erizocosmico**
Fixes #325

### CODE REVIEW

**Comment by ajnavarro** [comment]
@erizocosmico should add to the documentation the min needed bblfsh version?

**Comment by erizocosmico** [comment]
@ajnavarro totally true, let me fix that.

**Comment by erizocosmico** [comment]
Done @ajnavarro

**Comment by ajnavarro** [comment]
@erizocosmico can you rebase and merge, please?

**Comment by erizocosmico** [comment]
yup

**Comment by erizocosmico** [comment]
Done, will merge as soon as the build passes

**Pull request merged**
