### PR TITLE
*: commit_trees squash rules and tree_entries refactor

### LINKED ISSUE #268: Modify table: tree_entries
New columns:

Tree_entries Table
--
repository_id
tree_entry_name
blob_hash
tree_hash
tree_entry_mode

Also, tree_entry_name must only contain the name of the specific tree or tree entry, instead of all the concatenated names to reach a specific tree entry.

If the entry is a tree, blob_hash will be null, If the entry is a blob, tree_hash will be null.

### LINKED ISSUE #274: Delete relation UDFs and modify squash rule to work with relation tables
commit_has_tree()
commit_has_blob()
history_idx()

This should be done after all the changes on the existing tables, and the implementation of the new ones.

### PR DESCRIPTION
**Pull request by erizocosmico**
Depends on #285 

Partially closes #274 
Closes #268 

* Add commit_trees squash rule
* Refactor of how tree_entries table works
* Refactor of ref_commit squashes for better integration with this

### CODE REVIEW

**Comment by erizocosmico** [comment]
Can be reviewed now. Only review last commit.

**Comment by erizocosmico** [comment]
Rebased and conflicts resolved

**Comment by ajnavarro** [comment]
@erizocosmico rebase please

**Comment by erizocosmico** [comment]
Rebased again after merging files table PR

**Pull request merged**
